---
title: "Atlantic Coast Working Waterfronts from Delaware to Maine"
subtitle: "Tracking impacts of recent amendments to the Magnuson-Stevens Fishery Conservation and Managaement Act (MSA) on fish stock and regional livelihoods"
---

## Introduction

Commercial fishing is a key industry in the Northeast. Historically, fisheries were the primary employer in many towns, and cities grew up around the industry. Throughout the 20th and 21st centuries, commercial fishing had periods of boom and bust leading to declining towns and depopulation along the coast. Despite these fluctuations, commercial fishing is still important to the region both economically and culturally. The industry also has significant environmental externalities, including pollution, trophic system collapse and ocean warming. Managing fishery operations is essential to ensure long term resource availability but can have negative impacts in the short term on the economic viability of businesses. This is a question of balancing economy and livelihoods with sustainability. 

To this end, the Magnuson-Stevens Fishery Conservation and Management Act (MSA) is the primary law responsible for commercial fishery management in the United States. The federal government passed the act in 1976, and reauthorized it in 2007 and 2018. At the time of both re-authorizations, the federal government incorporated additional regulations. We are keen to understand what impacts the 2007 and 2018 amendments to the MSA have had on coastal communities in the Northeast and if the amendments were successful in conserving Atlantic fish stocks. To read more about the act, please click on the MSA Background tab on the left. 

## Proposal

With our analysis we hope to answer questions in two buckets: </p>  
 1. How were fish stock, GDP, and commercial fishing employment impacted by the two policy changes? Is there a regional pattern? Are there state-specific patterns?

 2. Where are the most important fisheries along the north Atlantic Coast and what factors define the most important fishing ports?

To identify trends we will need to look at data for a period that begins before the amendments came into effect and ends with the most recent data available. However, we are constrained by the data available through NOAA's StockSMART database - the most publically-accessible comprehensive repository on fisheries resource management. As such, we are looking at the time period between 2005 and 2022. 


SHOULD WE LINK TO EMLAB WORK? OR NO BC WE DIDN'T ASK FOR PERMISSION FROM SEAN AND KEITH?


