project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Atlantic Coast Working Waterfronts from Delaware to Maine"
  page-footer:
    left: "mlup@upenn.edu, cgustz@design.upenn.edu"
    right: "This page is built with 🐟 and [Quarto](https://quarto.org/)."

  sidebar:
    logo: "images/workingwaterfront_Maine.jpg"
    subtitle: "final project by Clarasophia Z. Gust & Mariya Lupandina, UPenn students in MUSA620."
    pinned: true
    align: center

    tools:
      - icon: globe
        href: https://www.fisheries.noaa.gov/topic/laws-policies/magnuson-stevens-act
        text: "NOAA Fishiries website"
      - icon: github
        href: https://github.com/m-lup/ne-fisheries/tree/main
        text: "website repository"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Introduction
      - MSABackground.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/1-FishstockLivelihood.ipynb
          - analysis/2-MajorFisheriesNE.ipynb
      - Conclusion.qmd
format:
  html:
    highlight-style: solarized
    theme: flatly
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
