---
title: "Atlantic Coast Working Waterfronts from Delaware to Maine"
subtitle: "Tracking impacts of recent amendments to the Magnuson-Stevens Fishery Conservation and Managaement Act (MSA) on fish stock and regional livelihoods"
---

## Introduction

Commercial fishing is a key industry in the Northeast. Historically, fisheries were the primary employer in many towns, and cities grew up around the industry. Throughout the 20th and 21st centuries, commercial fishing had periods of boom and bust leading to declining towns and depopulation along the coast. Despite these fluctuations, commercial fishing is still important to the region both economically and culturally. The industry also has significant environmental externalities, including pollution, trophic system collapse and ocean warming. Managing fishery operations is essential to ensure long term resource availability but can have negative impacts in the short term on the economic viability of businesses. This is a question of  balancing economy and livelihoods with sustainability. 

To this end, the Magnuson-Stevens Fishery Conservation and Management Act (MSA) is the primary law responsible for commercial fishery management in the United States. First passed in 1976, the MSA aims to (1) prevent overfishing, (2) rebuild overfished stocks, (3) ensure a safe and sustainable seafood supply, (4) increase long-term economic and social benefit, and (5) protect fish habitats needed for spawning, breeding, feeding and growing to maturity. The federal government reauthorized and strengthened the MSA in 2007. In 2018, the MSA was further amended by the Modernizing Recreational Fisheries Management Act to improve the accountability of mixed-use fisheries (companies that have commercial and recreational operations). We are keen to understand what impacts the 2007 and 2018 amendments to the MSA have had on coastal communities in the Northeast. 

We will be looking at the time period between 2005 and 2022 to include data before and after the amendments. We are also setting this time period based on the data available from NOAA’s StockSMART database, this is our constraining factor.  We are also using the project to supplement our work at the EMLab, which focuses on the coastal region from Delaware to Maine. Through the project we hope to learn more about a key socio-cultural facet of the Northeast coast that may inform our approach to designing nature-based infrastructures that brings environmental, economic and social benefits.


